# Generated by Django 5.0.6 on 2024-05-22 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("base", "0003_producto_unidades_x_paquete"),
    ]

    operations = [
        migrations.CreateModel(
            name="TablaScrap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url_Scrap", models.URLField()),
                ("frec_Scrap", models.PositiveIntegerField()),
                ("codigo_interno", models.CharField(max_length=50)),
                (
                    "Producto_base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.producto"
                    ),
                ),
            ],
        ),
    ]
