# Generated by Django 5.0.6 on 2024-05-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="precio",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="producto",
            name="stock_actual",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="producto",
            name="stock_minimo",
            field=models.IntegerField(default=10),
        ),
    ]
