# Generated by Django 5.0.6 on 2024-05-22 23:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_producto_precio_producto_stock_actual_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="unidades_x_paquete",
            field=models.IntegerField(default=0),
        ),
    ]
